mod 'boxen',    '0.2.0', :github_tarball => 'boxen/puppet-boxen'
mod 'homebrew', '0.2.0', :github_tarball => 'boxen/puppet-homebrew'
mod 'stdlib',   '3.0.0', :github_tarball => 'puppetlabs/puppetlabs-stdlib'
mod 'xquartz',  '0.0.2', :github_tarball => 'boxen/puppet-xquartz'
